name: Update publications from Google Scholar

on:
  schedule:
    - cron: "7 2 * * 1"   # weekly
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/scholar.yml"
      - "tools/fetch_scholar.py"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  update-pubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Auto-retry the fetch step (up to 3 attempts)
      - name: Fetch Google Scholar publications (with retry)
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 10
          command: python tools/fetch_scholar.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add publications.json
            git commit -m "Update publications.json from Google Scholar"
            git push
          else
            echo "No changes to commit."
          fi
